const mongoose = require('mongoose');

const orderItemSchema = new mongoose.Schema({
  product: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'Product',
    required: true
  },
  productName: {
    type: String,
    required: true
  },
  brand: {
    type: String,
    required: true
  },
  category: {
    type: String,
    required: true
  },
  quantity: {
    type: Number,
    required: true,
    min: [1, 'Quantity must be at least 1']
  },
  unitPrice: {
    type: Number,
    required: true,
    min: [0, 'Unit price cannot be negative']
  },
  vatRate: {
    type: Number,
    default: 10,
    min: [0, 'VAT rate cannot be negative'],
    max: [100, 'VAT rate cannot exceed 100%']
  },
  vatAmount: {
    type: Number,
    default: 0,
    min: [0, 'VAT amount cannot be negative']
  },
  totalPrice: {
    type: Number,
    required: true,
    min: [0, 'Total price cannot be negative']
  }
});

const orderSchema = new mongoose.Schema({
  orderNumber: {
    type: String,
    required: false, // Will be auto-generated by pre-save middleware
    unique: true
  },
  orderType: {
    type: String,
    enum: ['invoice', 'quotation', 'proforma', 'credit'],
    required: true
  },
  status: {
    type: String,
    enum: ['pending', 'confirmed', 'processing', 'shipped', 'delivered', 'cancelled', 'returned'],
    default: 'pending'
  },
  customer: {
    company: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'Company',
      required: true
    },
    companyName: {
      type: String,
      required: true
    },
    employee: {
      type: String,
      required: true
    },
    contactInfo: {
      name: {
        type: String,
        required: true
      },
      email: {
        type: String,
        required: true
      },
      phone: {
        type: String,
        required: false,
        default: 'N/A'
      },
      address: {
        type: String,
        required: true
      },
      city: {
        type: String,
        required: true
      }
    }
  },
  items: [orderItemSchema],
  pricing: {
    subtotal: {
      type: Number,
      required: true,
      min: [0, 'Subtotal cannot be negative']
    },
    deliveryCost: {
      type: Number,
      default: 0,
      min: [0, 'Delivery cost cannot be negative']
    },
    totalVat: {
      type: Number,
      default: 0,
      min: [0, 'Total VAT cannot be negative']
    },
    total: {
      type: Number,
      required: true,
      min: [0, 'Total cannot be negative']
    },
    currency: {
      type: String,
      default: 'BD'
    }
  },
  payment: {
    method: {
      type: String,
      enum: ['cash', 'visa', 'benefit', 'floos', 'credit'],
      required: true
    },
    status: {
      type: String,
      enum: ['pending', 'paid', 'failed', 'refunded'],
      default: 'pending'
    },
    paidAt: {
      type: Date,
      default: null
    },
    transactionId: {
      type: String,
      default: null
    }
  },
  orderStatus: {
    type: String,
    enum: ['Normal', 'Urgent', 'Rush', 'Emergency'],
    default: 'Normal'
  },
  accountantReviewStatus: {
    type: String,
    enum: ['PENDING_REVIEW', 'UNDER_REVIEW', 'APPROVED', 'REJECTED', 'CANCELLED'],
    default: 'PENDING_REVIEW'
  },
  invoicePdf: {
    url: {
      type: String,
      trim: true
    },
    public_id: {
      type: String,
      trim: true
    }
  },
  shipping: {
    address: {
      type: String,
      required: true
    },
    city: {
      type: String,
      required: true
    },
    country: {
      type: String,
      default: 'Bahrain'
    },
    trackingNumber: {
      type: String,
      default: null
    },
    estimatedDelivery: {
      type: Date,
      default: null
    },
    deliveredAt: {
      type: Date,
      default: null
    }
  },
  notes: {
    customer: {
      type: String,
      trim: true,
      maxlength: [1000, 'Customer notes cannot exceed 1000 characters']
    },
    internal: {
      type: String,
      trim: true,
      maxlength: [1000, 'Internal notes cannot exceed 1000 characters']
    }
  },
  createdBy: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User',
    required: true
  },
  updatedBy: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User',
    default: null
  }
}, {
  timestamps: true
});

// Index for better performance
orderSchema.index({ orderNumber: 1 });
orderSchema.index({ 'customer.company': 1 });

// Pre-save hook to sync accountantReviewStatus to status field
// This ensures admin and salesman roles see the updated status when accountant updates it
orderSchema.pre('save', function(next) {
  // Only sync if accountantReviewStatus is being modified and status is not explicitly set
  if (this.isModified('accountantReviewStatus') && this.accountantReviewStatus) {
    // Map accountantReviewStatus to regular status
    const statusMap = {
      'PENDING_REVIEW': 'pending',
      'UNDER_REVIEW': 'processing',
      'APPROVED': 'confirmed',
      'REJECTED': 'cancelled',
      'CANCELLED': 'cancelled'
    };
    
    // Update status field to match accountantReviewStatus (unless status was explicitly modified)
    if (!this.isModified('status') || this.status === this.constructor.schema.paths.status.defaultValue) {
      this.status = statusMap[this.accountantReviewStatus] || this.status;
    }
  }
  next();
});
orderSchema.index({ status: 1 });
orderSchema.index({ orderType: 1 });
orderSchema.index({ 'payment.method': 1 });
orderSchema.index({ orderStatus: 1 });
orderSchema.index({ createdAt: -1 });

// Pre-save middleware to generate order number and sync accountantReviewStatus to status
orderSchema.pre('save', async function(next) {
  // Generate order number for new orders
  if (this.isNew && !this.orderNumber) {
    const count = await this.constructor.countDocuments();
    const date = new Date();
    const year = date.getFullYear();
    const month = String(date.getMonth() + 1).padStart(2, '0');
    const day = String(date.getDate()).padStart(2, '0');
    this.orderNumber = `ORD-${year}${month}${day}-${String(count + 1).padStart(4, '0')}`;
  }
  
  // Sync accountantReviewStatus to status field when accountantReviewStatus is modified
  // This ensures admin and salesman roles see the updated status when accountant updates it
  if (this.isModified('accountantReviewStatus') && this.accountantReviewStatus) {
    // Map accountantReviewStatus to regular status
    const statusMap = {
      'PENDING_REVIEW': 'pending',
      'UNDER_REVIEW': 'processing',
      'APPROVED': 'confirmed',
      'REJECTED': 'cancelled',
      'CANCELLED': 'cancelled'
    };
    
    // Update status field to match accountantReviewStatus (unless status was explicitly modified in the same operation)
    const mappedStatus = statusMap[this.accountantReviewStatus];
    if (mappedStatus && (!this.isModified('status') || this.status === 'pending')) {
      this.status = mappedStatus;
    }
  }
  
  next();
});

// Virtual for order summary
orderSchema.virtual('summary').get(function() {
  return {
    orderNumber: this.orderNumber,
    orderType: this.orderType,
    status: this.status,
    total: this.pricing.total,
    itemCount: this.items.length,
    customer: this.customer.companyName
  };
});

// Method to calculate totals
orderSchema.methods.calculateTotals = function() {
  let subtotal = 0;
  let totalVat = 0;
  
  this.items.forEach(item => {
    const itemSubtotal = item.unitPrice * item.quantity;
    const itemVat = itemSubtotal * (item.vatRate / 100);
    
    subtotal += itemSubtotal;
    totalVat += itemVat;
    
    item.vatAmount = itemVat;
    item.totalPrice = itemSubtotal + itemVat;
  });
  
  this.pricing.subtotal = subtotal;
  this.pricing.totalVat = totalVat;
  this.pricing.total = subtotal + this.pricing.deliveryCost + totalVat;
  
  return this;
};

// Method to update status
orderSchema.methods.updateStatus = function(newStatus, updatedBy) {
  this.status = newStatus;
  this.updatedBy = updatedBy;
  
  if (newStatus === 'delivered') {
    this.shipping.deliveredAt = new Date();
  }
  
  return this.save();
};

// Static method to get orders by company
orderSchema.statics.getByCompany = function(companyId, limit = 10, skip = 0) {
  return this.find({ 'customer.company': companyId })
    .sort({ createdAt: -1 })
    .limit(limit)
    .skip(skip)
    .populate('items.product', 'name sku brand category')
    .populate('createdBy', 'name email');
};

// Static method to get order statistics
orderSchema.statics.getStatistics = async function(query = {}) {
  // Build match stage for filtering
  const matchStage = Object.keys(query).length > 0 ? [{ $match: query }] : [];
  
  const stats = await this.aggregate([
    ...matchStage,
    {
      $group: {
        _id: null,
        totalOrders: { $sum: 1 },
        totalRevenue: { $sum: '$pricing.total' },
        averageOrderValue: { $avg: '$pricing.total' }
      }
    }
  ]);
  
  const statusStats = await this.aggregate([
    ...matchStage,
    {
      $group: {
        _id: '$status',
        count: { $sum: 1 }
      }
    }
  ]);
  
  return {
    overview: stats[0] || { totalOrders: 0, totalRevenue: 0, averageOrderValue: 0 },
    statusBreakdown: statusStats
  };
};

module.exports = mongoose.model('Order', orderSchema);
